version: '3.3'

services:
  mongodb:
    build:
      context: .
      dockerfile: docker/mongodb.dockerfile
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    entrypoint: ["mongod", "--bind_ip", "0.0.0.0"]
    restart: always

  spectroman:
    build:
      context: .
      dockerfile: docker/spectroman.dockerfile
    volumes:
      - /var/lib/postgresql/data
    depends_on:
      - mongodb

volumes:
  db-data:
